export const COLLECTIONS = {
  USERS: 'users',
  FAVORITES: 'favorites',
  RATINGS: 'ratings',
  COMMENTS: 'comments',
  USER_TAGS: 'userTags',
  FEEDBACK: 'feedback',
  CUSTOM_TAGS: 'customTags',
  CONFIG: 'config',
  DAILY_METRICS: 'dailyMetrics',
  ABUSE_LOGS: 'abuseLogs',
  COMMENT_LIKES: 'commentLikes',
  MENU_PHOTOS: 'menuPhotos',
  PRICE_LEVELS: 'priceLevels',
  USER_RANKINGS: 'userRankings',
  NOTIFICATIONS: 'notifications',
} as const;
