export const COLLECTIONS = {
  USERS: 'users',
  FAVORITES: 'favorites',
  RATINGS: 'ratings',
  COMMENTS: 'comments',
  USER_TAGS: 'userTags',
  FEEDBACK: 'feedback',
  CUSTOM_TAGS: 'customTags',
  CONFIG: 'config',
  DAILY_METRICS: 'dailyMetrics',
  ABUSE_LOGS: 'abuseLogs',
  COMMENT_LIKES: 'commentLikes',
  MENU_PHOTOS: 'menuPhotos',
  PRICE_LEVELS: 'priceLevels',
  USER_RANKINGS: 'userRankings',
  NOTIFICATIONS: 'notifications',
  USER_SETTINGS: 'userSettings',
  PERF_METRICS: 'perfMetrics',
  SHARED_LISTS: 'sharedLists',
  LIST_ITEMS: 'listItems',
  TRENDING_BUSINESSES: 'trendingBusinesses',
  CHECKINS: 'checkins',
  FOLLOWS: 'follows',
  ACTIVITY_FEED: 'activityFeed',
  RECOMMENDATIONS: 'recommendations',
  RATE_LIMITS: '_rateLimits',
} as const;
